name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - main

# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag autogen-studio:$(date +%s)
    
    - name: Store the image as a tarball
      run: docker save autogen-studio:$(date +%s) > autogen-studio.tar

    - name: Include the Docker image in the workflow as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: autogen-studio
        path: autogen-studio.tar