name: Docker Image CI

on:
  pull_request:  
    branches:
      - master
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag autogen-studio:$(date +%s)
    
    - name: Store the image as a tarball
      run: docker save autogen-studio > autogen-studio.tar

    - name: Include the Docker image in the workflow as an artifact
      uses: actions/upload-artifact@v2
      with:
        name: autogen-studio
        path: autogen-studio.tar
    
    - name: Login to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Upload the Docker image to the Container registry
      if: github.event_name != 'pull_request'
      id: push
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: ${{ env.IMAGE_NAME }}
        addLatest: true
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
