name: Docker Image CI

on:
  pull_request:  
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag autogen-studio:$(date +%s) --build-arg REPO_URL=https://github.com/${{ github.repository }}
    
    - name: Login to the Container registry
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Upload the Docker image to the Container registry
      if: github.event_name != 'pull_request'
      id: push
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: ${{ env.IMAGE_NAME }}
        addLatest: true
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
