name: Docker Image CI

on:
  pull_request:  
    branches:
      - master
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.event.repository.name }}
  PACKAGE_NAME: autogenstudio

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Get the latest version number of a given pip package
      id: get_version
      run: |
        VERSION=$(curl -s https://pypi.org/pypi/${{ env.PACKAGE_NAME }}/json | jq -r .info.version)
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

    - name: Compare PIP version with last created package in the container registry
      id: check_version
      run: |
        echo "Checking if the version exists in the container registry..."
        echo "Version: ${{ steps.get_version.outputs.VERSION }}"
        ORG=$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')
        echo "Image: ${{ env.REGISTRY }}/$ORG/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }}"
        if docker manifest inspect ${{ env.REGISTRY }}/$ORG/${{ env.IMAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} > /dev/null 2>&1; then
          echo "The version exists in the container registry."
          echo "VERSION_EXISTS=true" >> $GITHUB_OUTPUT
        else
          echo "The version does not exist in the container registry."
          echo "VERSION_EXISTS=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ env.PACKAGE_NAME }}:${{ steps.get_version.outputs.VERSION }} --build-arg REPO_URL=https://github.com/${{ github.repository }}
    
    - name: Login to the container registry
      if: github.event_name != 'pull_request' && steps.check_version.outputs.VERSION_EXISTS == 'false'
      uses: docker/login-action@v3.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload the Docker image to the container registry
      if: github.event_name != 'pull_request' && steps.check_version.outputs.VERSION_EXISTS == 'false'
      id: push
      uses: mr-smithers-excellent/docker-build-push@v6.4
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ steps.get_version.outputs.VERSION }}, latest
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
